### PR TITLE
Add in-app purchases

### PR DESCRIPTION
**Pull request by williamhogman**
This pull-request adds in-app purchases.

Some partners are want to start writing apps using IAP so we need to update the client library to add this functionality.

Ping: @alexmic

### CODE REVIEW

**Comment by alexmic** [comment]
Hmm, the tests are failing: 

```
E           assert {'message': '...@tictail.com'} == {'message': 'B...@tictail.com'}
E             Omitting 3 identical items, use -v to show
E             Differing items:
E             {'params': {'email': 'Missing required parameter email in json'}} != {'params': {'email': 'email is required in json'}}
```

**Comment by parhamfh** [comment]
I'll take a look at this tomorrow!

**Comment by alexmic** [comment]
@parhamfh did you get a chance to look at the tests or should I?

**Comment by parhamfh** [comment]
@alexmic have not had the time to take a look at this, so if you have the time you are most welcome to have a look :+1:

**Comment by ptz0n** [comment]
Fix incoming..

**Pull request closed without merging**
